<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>75752143-f774-4667-a026-73e40054cab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div/div[2]/form/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.bg-blue-500.text-white.rounded-md.px-2.py-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84ca93e8-99a4-4223-8f15-f75082f52ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-blue-500 text-white rounded-md px-2 py-1</value>
      <webElementGuid>e7578055-dd06-49aa-97a9-c23810d7a375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Submit </value>
      <webElementGuid>7a8e1b3d-0fad-4be9-a1a6-74ea85720690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12&quot;]/div[@class=&quot;relative py-3 sm:max-w-xl sm:mx-auto&quot;]/div[@class=&quot;relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20&quot;]/div[@class=&quot;max-w-md mx-auto&quot;]/div[@class=&quot;divide-y divide-gray-200&quot;]/form[1]/div[@class=&quot;py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7&quot;]/div[@class=&quot;relative&quot;]/button[@class=&quot;bg-blue-500 text-white rounded-md px-2 py-1&quot;]</value>
      <webElementGuid>f76d3a10-fd33-4664-bc05-bfc0084f50b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div[2]/form/div/div[3]/button</value>
      <webElementGuid>d02acecc-fcdd-461a-8ae2-267818b94cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>3fa70600-43e8-4c68-aec7-bdbda68163bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::button[1]</value>
      <webElementGuid>4a1068f4-1eef-451a-a485-9a2325719349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>3145bbe4-f001-4131-a746-04331e9452a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ce7b6795-7b5a-4ef4-ae7a-bcf1957895e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Submit ' or . = ' Submit ')]</value>
      <webElementGuid>56c83415-5870-42d2-8d79-85f03ea3ecdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
