<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_input</name>
   <tag></tag>
   <elementGuidId>ade55b8f-c888-4ac2-a4ed-a221e598ef6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0df584ec-1059-40e3-b39a-85297460b425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-2 border-gray-300 bg-white h-10 pl-2 pr-8 rounded-lg text-sm focus:outline-none</value>
      <webElementGuid>33f8399e-c9dd-4fd2-8e0b-f0940c159b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d696b1e3-e7e1-46d9-b940-77788fc050fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>088d83cc-8bec-41f5-9500-ac84a15f454b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f5fd85e-a666-4166-a7a3-3d21927268af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[@class=&quot;flex items-center justify-between flex-wrap py-4 lg:px-12 shadow border-solid border-t-2 border-blue-700&quot;]/div[@class=&quot;menu w-full lg:block flex-grow lg:flex lg:items-center lg:w-auto lg:px-3 px-8&quot;]/div[@class=&quot;relative mx-auto text-gray-600 lg:block hidden&quot;]/form[1]/input[@class=&quot;border-2 border-gray-300 bg-white h-10 pl-2 pr-8 rounded-lg text-sm focus:outline-none&quot;]</value>
      <webElementGuid>43de93a3-f8b2-42ee-b30b-ffff3ee08767</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input']</value>
      <webElementGuid>159a6edd-b820-4a63-812e-69820923a719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav/div[2]/div[3]/form/input</value>
      <webElementGuid>a798b3ea-2b82-4b9f-b7bf-d3f632f331de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>af6e3a9d-272e-49dd-9b39-2093dbe8c9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @placeholder = 'Search' and @name = 'input']</value>
      <webElementGuid>67a13af8-775c-4b40-90e6-3957eb80de5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
